-- CreateTable
CREATE TABLE "Set" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "memo" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "User" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Flower" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "userId" INTEGER NOT NULL,
    "setId" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "rarity" INTEGER NOT NULL,
    "rank" INTEGER NOT NULL,
    "main" TEXT NOT NULL,
    "atk" INTEGER NOT NULL DEFAULT 0,
    "atkPer" REAL NOT NULL DEFAULT 0,
    "def" INTEGER NOT NULL DEFAULT 0,
    "defPer" REAL NOT NULL DEFAULT 0,
    "critRate" REAL NOT NULL DEFAULT 0,
    "critDmg" REAL NOT NULL DEFAULT 0,
    "eneChar" REAL NOT NULL DEFAULT 0,
    "eneMas" REAL NOT NULL DEFAULT 0,
    "hp" INTEGER NOT NULL DEFAULT 0,
    "hpPer" REAL NOT NULL DEFAULT 0,
    CONSTRAINT "Flower_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Flower_setId_fkey" FOREIGN KEY ("setId") REFERENCES "Set" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Plume" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "userId" INTEGER NOT NULL,
    "setId" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "rarity" INTEGER NOT NULL,
    "rank" INTEGER NOT NULL,
    "main" TEXT NOT NULL,
    "atk" INTEGER NOT NULL DEFAULT 0,
    "atkPer" REAL NOT NULL DEFAULT 0,
    "def" INTEGER NOT NULL DEFAULT 0,
    "defPer" REAL NOT NULL DEFAULT 0,
    "critRate" REAL NOT NULL DEFAULT 0,
    "critDmg" REAL NOT NULL DEFAULT 0,
    "eneChar" REAL NOT NULL DEFAULT 0,
    "eneMas" REAL NOT NULL DEFAULT 0,
    "hp" INTEGER NOT NULL DEFAULT 0,
    "hpPer" REAL NOT NULL DEFAULT 0,
    CONSTRAINT "Plume_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Plume_setId_fkey" FOREIGN KEY ("setId") REFERENCES "Set" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Sans" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "userId" INTEGER NOT NULL,
    "setId" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "rarity" INTEGER NOT NULL,
    "rank" INTEGER NOT NULL,
    "main" TEXT NOT NULL,
    "atk" INTEGER NOT NULL DEFAULT 0,
    "atkPer" REAL NOT NULL DEFAULT 0,
    "def" INTEGER NOT NULL DEFAULT 0,
    "defPer" REAL NOT NULL DEFAULT 0,
    "critRate" REAL NOT NULL DEFAULT 0,
    "critDmg" REAL NOT NULL DEFAULT 0,
    "eneChar" REAL NOT NULL DEFAULT 0,
    "eneMas" REAL NOT NULL DEFAULT 0,
    "hp" INTEGER NOT NULL DEFAULT 0,
    "hpPer" REAL NOT NULL DEFAULT 0,
    CONSTRAINT "Sans_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Sans_setId_fkey" FOREIGN KEY ("setId") REFERENCES "Set" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Goblet" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "userId" INTEGER NOT NULL,
    "setId" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "rarity" INTEGER NOT NULL,
    "rank" INTEGER NOT NULL,
    "main" TEXT NOT NULL,
    "atk" INTEGER NOT NULL DEFAULT 0,
    "atkPer" REAL NOT NULL DEFAULT 0,
    "def" INTEGER NOT NULL DEFAULT 0,
    "defPer" REAL NOT NULL DEFAULT 0,
    "critRate" REAL NOT NULL DEFAULT 0,
    "critDmg" REAL NOT NULL DEFAULT 0,
    "eneChar" REAL NOT NULL DEFAULT 0,
    "eneMas" REAL NOT NULL DEFAULT 0,
    "hp" INTEGER NOT NULL DEFAULT 0,
    "hpPer" REAL NOT NULL DEFAULT 0,
    CONSTRAINT "Goblet_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Goblet_setId_fkey" FOREIGN KEY ("setId") REFERENCES "Set" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Circlet" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "userId" INTEGER NOT NULL,
    "setId" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "rarity" INTEGER NOT NULL,
    "rank" INTEGER NOT NULL,
    "main" TEXT NOT NULL,
    "atk" INTEGER NOT NULL DEFAULT 0,
    "atkPer" REAL NOT NULL DEFAULT 0,
    "def" INTEGER NOT NULL DEFAULT 0,
    "defPer" REAL NOT NULL DEFAULT 0,
    "critRate" REAL NOT NULL DEFAULT 0,
    "critDmg" REAL NOT NULL DEFAULT 0,
    "eneChar" REAL NOT NULL DEFAULT 0,
    "eneMas" REAL NOT NULL DEFAULT 0,
    "hp" INTEGER NOT NULL DEFAULT 0,
    "hpPer" REAL NOT NULL DEFAULT 0,
    CONSTRAINT "Circlet_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Circlet_setId_fkey" FOREIGN KEY ("setId") REFERENCES "Set" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Preset" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "flowerId" INTEGER NOT NULL,
    "plumeId" INTEGER NOT NULL,
    "sansId" INTEGER NOT NULL,
    "gobletId" INTEGER NOT NULL,
    "circletId" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    CONSTRAINT "Preset_flowerId_fkey" FOREIGN KEY ("flowerId") REFERENCES "Flower" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Preset_plumeId_fkey" FOREIGN KEY ("plumeId") REFERENCES "Plume" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Preset_sansId_fkey" FOREIGN KEY ("sansId") REFERENCES "Sans" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Preset_gobletId_fkey" FOREIGN KEY ("gobletId") REFERENCES "Goblet" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Preset_circletId_fkey" FOREIGN KEY ("circletId") REFERENCES "Circlet" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Tag" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "color" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "_PresetToTag" (
    "A" INTEGER NOT NULL,
    "B" INTEGER NOT NULL,
    CONSTRAINT "_PresetToTag_A_fkey" FOREIGN KEY ("A") REFERENCES "Preset" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_PresetToTag_B_fkey" FOREIGN KEY ("B") REFERENCES "Tag" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "_PresetToTag_AB_unique" ON "_PresetToTag"("A", "B");

-- CreateIndex
CREATE INDEX "_PresetToTag_B_index" ON "_PresetToTag"("B");
